from langchain_core.messages import AIMessage, HumanMessage, SystemMessage
from .multi_agent import llm, AgentState

def run_reasoning_agent(state: AgentState) -> str:
    """
    Run the reasoning agent to generate a detailed explaination about the process of generating answer for the user's query.
    Args:
        state (AgentState): The current state of the agent containing messages and context.
    Returns:
        reasoning (str): The detailed explaination generated by the reasoning agent.
    """
    agent_used = []
    if state.get("route", "") == "documents":
        agent_used = ["router_agent", "extract_docs_agent", "documents_agent"]
    else:
        agent_used = ["router_agent", "generate_subqueries_agent", "retrieve_laws_agent", "laws_agent"]
    
    answer = state.get("messages", [])[-1]
    if not isinstance(answer, AIMessage):
        raise ValueError("run_reasoning_agent: last message is not an AIMessage")
    for message in reversed(state.get("messages", [])):
        if isinstance(message, HumanMessage):
            user_query = message.content
            break
    route = state.get("route", "")
    if route == "documents":
        context = state.get("docs_context", "")
    else:
        context = state.get("laws_context", "")
    system_prompt = (
    f"""
    Bạn là một trợ lý ngôn ngữ chuyên về giải thích quá trình suy luận. 
    Nhiệm vụ của bạn là tạo ra một giải thích chi tiết về cách câu trả lời cuối cùng được tạo ra cho truy vấn của người dùng, dựa trên các tác nhân đã được sử dụng trong quá trình này.

    THÔNG TIN ĐẦU VÀO:
    - Truy vấn của người dùng: {user_query}
    - Route đã chọn: {route}
    - Ngữ cảnh được sử dụng: {context}
    - Câu trả lời cuối cùng: {answer.content}
    - Các tác nhân đã sử dụng trong quá trình: {', '.join(agent_used)}

    VAI TRÒ CỦA MỖI TÁC NHÂN:
    - router_agent: Xác định con đường phù hợp dựa trên truy vấn của người dùng (trả lời dựa trên tài liệu hoặc dữ liệu luật), sinh ra route.
    - extract_docs_agent: Trích xuất các thông tin liên quan từ kho tài liệu dựa trên truy vấn của người dùng, sinh ra ngữ cảnh.
    - documents_agent: Tạo câu trả lời dựa trên các thông tin đã trích xuất, sinh ra câu trả lời cuối cùng.
    - generate_subqueries_agent: Tạo các truy vấn phụ từ truy vấn chính để tìm kiếm thông tin luật pháp liên quan, sinh ra các truy vấn phụ. 
    - retrieve_laws_agent: Tìm kiếm và thu thập các điều luật liên quan trên dữ liệu luật dựa trên các truy vấn phụ, sinh ra ngữ cảnh.
    - laws_agent: Tạo câu trả lời dựa trên các điều luật đã thu thập, sinh ra câu trả lời cuối cùng.

    YÊU CẦU GIẢI THÍCH QUÁ TRÌNH SUY LUẬN:
    - Phần 1: Mô tả tổng quan về quá trình suy luận: vai trò tác nhân, cách thông tin ngữ cảnh được dùng để tạo câu trả lời.
    - Phần 2: Giải thích trình bày các bước sinh ra câu trả lời một cách rõ ràng và logic
    - Trình bày giải thích trên dưới dạng đoạn văn mạch lạc.
    """
    )
    system_message = SystemMessage(content= system_prompt)
    user_message = HumanMessage(content= "Hãy tạo ra một giải thích chi tiết về quá trình suy luận để tạo ra câu trả lời cuối cùng.")
    all_messages = [system_message, user_message]
    response = llm.invoke(all_messages)
    return response.content
